# https://taskfile.dev

version: '3'

vars:
  BIN_NAME: advent

env:
  GOPRIVATE: github.com/automagicninja/advent-of-code-2022

tasks:
  default:
    cmds:
      - { task: build }
      - { task: test }
    silent: true

  deps:
    cmds:
      - go mod tidy
      - go get -u -t ./...
      - go vet ./...
    sources:
      - "*.go"
      - "**/*.go"

  build:
    cmds:
      - { task: deps }
      - go build -o "{{.BIN_NAME}}"
    sources:
      - "*.go"
      - "**/*.go"

  test:
    deps:
      - build
    cmds:
      - go test ./...
    sources:
      - "*_test.go"
      - "**/*_test.go"

  run:
    deps:
      - build
    cmds:
      - ./{{.BIN_NAME}} {{.CLI_ARGS}}
