// Code generated by "stringer -type Outcome"; DO NOT EDIT.

package rps

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Loss-0]
	_ = x[Draw-3]
	_ = x[Win-6]
}

const (
	_Outcome_name_0 = "Loss"
	_Outcome_name_1 = "Draw"
	_Outcome_name_2 = "Win"
)

func (i Outcome) String() string {
	switch {
	case i == 0:
		return _Outcome_name_0
	case i == 3:
		return _Outcome_name_1
	case i == 6:
		return _Outcome_name_2
	default:
		return "Outcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
